"""
a2a_agent/prompts/prior_auth.py — Prior authorization letter template

Template for generating human-readable prior auth draft letters.
"""

from __future__ import annotations


PRIOR_AUTH_LETTER_TEMPLATE = """
PRIOR AUTHORIZATION REQUEST

Date: {date}
Patient: {patient_name} (ID: {patient_id})
DOB: {birth_date} | Gender: {gender}

REQUESTED ITEM:
{requested_item}

DIAGNOSIS:
Primary: {primary_diagnosis} (ICD-10: {icd10_code}, SNOMED: {snomed_code})

CLINICAL JUSTIFICATION:
{clinical_narrative}

SUPPORTING DOCUMENTATION:
{supporting_docs}

PAYER CRITERIA ASSESSMENT:
{criteria_assessment}

MISSING ITEMS:
{missing_items}

CURRENT MEDICATIONS:
{current_medications}

RELEVANT LAB RESULTS:
{relevant_labs}

DRUG INTERACTIONS:
{interactions}

---
CONFIDENCE LEVEL: {confidence_level}
CONFIDENCE SCORE: {confidence_score}/100

⚠️ PHYSICIAN REVIEW REQUIRED ⚠️
This is an AI-generated draft. A physician must review and approve all content before submission.

Generated by AuthClear v1.0 on {generated_at}
Model: {model_version}
"""
