"""
shared/models/prior_auth.py — Prior Authorization data models

Pydantic models for prior authorization drafts and related data.
Used by the A2A Agent to structure outputs.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field

from shared.models.patient import LabResult


class ConfidenceLevel(str, Enum):
    """Confidence level based on completeness and quality of documentation."""

    HIGH = "high"                  # >= 0.90
    MEDIUM = "medium"              # >= 0.70
    LOW = "low"                    # >= 0.50
    INSUFFICIENT = "insufficient"  # < 0.50


class ConfidenceBreakdown(BaseModel):
    """
    Breakdown of confidence score by section.
    Used for transparent, auditable confidence calculation.
    """

    section: str                     # Section name (e.g., "diagnosis_mapping")
    sub_score: float                 # Points earned in this section
    max_score: float                 # Maximum possible points for this section
    rationale: str                   # Explanation of how score was calculated


class SupportingDoc(BaseModel):
    """A supporting document or data point for the prior auth request."""

    doc_type: str = ""     # lab_result | medication_history | clinical_note
    description: str = ""
    date: str | None = None
    status: str = "present"  # present | missing | outdated
    value: str | None = None
    fhir_resource_id: str | None = None      # Citation back to FHIR bundle
    auto_populated: bool = True              # Whether auto-extracted from FHIR


class MissingItem(BaseModel):
    """
    An item required by payer criteria that is missing from patient record.

    Updated to match agents.md Section 5 specification.
    """

    criterion: str = ""              # Which payer criterion this satisfies
    description: str = ""            # What is missing
    physician_action: str = ""       # Exactly what the physician must do
    blocking: bool = False           # True = cannot submit without this
    required_by: str = ""            # Payer criterion reference (for backward compat)


class PatientSummary(BaseModel):
    """High-level patient summary for the prior auth draft."""

    patient_name: str = ""
    patient_id: str = ""
    primary_diagnosis: str = ""
    icd10_code: str = ""
    snomed_code: str | None = None
    relevant_labs: list[LabResult | dict] = Field(default_factory=list)  # Can be LabResult objects or dicts
    current_medications: list[str | dict] = Field(default_factory=list)  # Can be simple strings or detailed dicts


class RequestedItemDetails(BaseModel):
    """Details about the drug/procedure being requested."""

    item_name: str = ""
    rxnorm_id: str | None = None
    drug_class: str | None = None
    cpt_hcpcs_code: str | None = None
    ndc_code: str | None = None
    typical_indications: list[str] = Field(default_factory=list)
    interactions_flagged: list[dict] = Field(default_factory=list)


class ClinicalJustification(BaseModel):
    """Clinical justification for the prior auth request."""

    diagnosis_meets_criteria: bool = False
    criteria_satisfied: list[str] = Field(default_factory=list)
    criteria_not_satisfied: list[str] = Field(default_factory=list)
    narrative: str = ""               # Human-readable justification


class PriorAuthDraft(BaseModel):
    """
    Complete prior authorization draft generated by the A2A Agent.

    CRITICAL INVARIANT: human_review_required is ALWAYS True.
    This ensures regulatory compliance (TX SB 490, AZ HB 2417, MD HB 1174).

    Updated to match agents.md Section 5 specification.
    """

    task_id: str
    schema_version: str = "2.0"

    # Patient
    patient_summary: PatientSummary

    # Request
    requested_item_details: RequestedItemDetails

    # Clinical
    clinical_justification: ClinicalJustification
    supporting_documentation: list[SupportingDoc] = Field(default_factory=list)
    missing_items: list[MissingItem] = Field(default_factory=list)

    # Scoring (agents.md Section 4)
    confidence_breakdown: list[ConfidenceBreakdown] = Field(default_factory=list)
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    confidence_level: ConfidenceLevel

    # Submission
    draft_letter: str = ""

    # Safety
    drug_interactions: list[dict] = Field(default_factory=list)
    human_review_required: bool = Field(default=True, frozen=True)

    # Metadata
    payer: str = "generic"
    urgency: str = "standard"
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    model_version: str = "claude-sonnet-4-20250514"
    fhir_bundle_hash: str | None = None          # SHA-256 of input bundle for audit trail
    tool_calls_made: list[str] = Field(default_factory=list)  # Audit log: which MCP tools were called
    warnings: list[str] = Field(default_factory=list)

    def __init__(self, **data):
        """Ensure human_review_required is always True."""
        data['human_review_required'] = True
        super().__init__(**data)

    class Config:
        json_schema_extra = {
            "example": {
                "task_id": "task-abc123",
                "patient_summary": {
                    "patient_name": "Maria González",
                    "patient_id": "synthetic-001",
                    "primary_diagnosis": "Type 2 diabetes mellitus",
                    "icd10_code": "E11.9",
                    "snomed_code": "44054006"
                },
                "requested_item_details": {
                    "item_name": "Ozempic (semaglutide)",
                    "rxnorm_id": "2200660",
                    "drug_class": "GLP-1 receptor agonist",
                    "cpt_hcpcs_code": "J0173"
                },
                "clinical_justification": {
                    "diagnosis_meets_criteria": True,
                    "criteria_satisfied": ["HbA1c > 7.5%", "BMI > 30", "Metformin trial documented"],
                    "criteria_not_satisfied": ["Second oral agent trial missing"],
                    "narrative": "Patient meets most criteria but lacks documented second oral agent trial."
                },
                "confidence_score": 0.72,
                "confidence_level": "medium",
                "human_review_required": True,
                "warnings": ["Second oral agent trial not documented"]
            }
        }
